#ifndef RAPIDMATCH_STREAMING_CONFIG_H
#define RAPIDMATCH_STREAMING_CONFIG_H
#define ENABLE_PERFORMANCE_COUNTERS

#define EXECUTION_MODE 0
extern bool g_exit;

#ifndef PHASE1_DEBUG_COMPARE_PLAIN
#define PHASE1_DEBUG_COMPARE_PLAIN 0
#endif

#ifndef RECORD_PHASE1_SUBQUERY_HITS
#define RECORD_PHASE1_SUBQUERY_HITS 0
#endif

#ifndef PRINT_PHASE1_DETAIL_METRICS
#define PRINT_PHASE1_DETAIL_METRICS 1
#endif


#endif 
