#ifndef SUBGRAPHMATCHING_CONFIG_H
#define SUBGRAPHMATCHING_CONFIG_H
#define OPTIMIZED_LABELED_GRAPH 1
#define MAXIMUM_QUERY_GRAPH_SIZE 32
#define HASH_TABLE_RATIO 1.2
#define HYBRID 0
#define SI 0
#define RELATION_STRUCTURE 0
#define FAILING_SET_PRUNING
#define COLLECT_FAIL_SI_STATISTICS
#define COLLECT_INVALID_PR_STATISTICS
#define COLLECT_SI_STATISTICS
#define OUTPUT_OPTIMIZATION
#define NANOSECTOSEC(elapsed_time) ((elapsed_time)/(double)1000000000)
#endif 
